main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Recent Change
    pageRef: /recent-change/
    weight: 20
  - name: Random Page
    url: random-page.html
    weight: 30
  - name: Tags
    pageRef: /tags/

social:
  - name: Twitter X
    url: https://example.com/
    params: {icon: "twitter-x"}
    weight: 10
  - name: Instagram
    url: https://example.com/
    params: {icon: "instagram"}
    weight: 20
  - name: Facebook
    url: https://example.com/
    params: {icon: "facebook"}
    weight: 30
  - name: Discord
    url: https://example.com/
    params: {icon: "discord"}
    weight: 40
  - name: Github
    url: https://example.com/
    params: {icon: "github"}
    weight: 50
  - name: Rss Feed
    url: index.xml
    params: {icon: "rss"}
    weight: 50

documents:
  - name: About Putra
    url: /about
    weight: 10
  - name: Disclaimer
    url: /disclaimer
    weight: 20
  - name: License
    url: /license
    weight: 30
  - name: Privacy Policy
    url: /privacy-policy
    weight: 40
  - name: Credits
    url: /credits
    weight: 50
  - name: Email
    url: mailto:masputrawae.official@gmail.com
    weight: 60
