baseURL: https://masputrawae.github.io/
languageCode: id
title: My Notes
timeZone: Asia/Jakarta
enableEmoji: true
enableGitInfo: true

#===================
# CASCADE
#===================
cascade:
  - _target:
      path: /dummy/**
    repoBasePath: notes
  - _target:
      path: '{/about,/disclaimer,/license,/privacy-policy}'
    repoBasePath: main-pages

#===================
# TAXONOMIES
#===================
taxonomies:
  tag: tags
  category: categories
  stage: stage
  source: source

#===================
# CUSTOM OUTPUT
#===================
mediaType: 'application/json'
outputFormats:
  search:
    mediaType: 'application/json'
    baseName: 'search'
    isPlainText: true
    notAlternative: true

  manifest:
    mediaType            : 'application/json'
    baseName             : 'manifest'
    isPlainText          : true
    notAlternative       : true

  random-page:
    mediaType            : 'text/html'
    baseName             : 'random-page'
    isPlainText          : true
    notAlternative       : true

outputs:
  home:
    - html
    - rss
    - sitemap
    - random-page
    - search
    - manifest

#===================
# MODULE & MOUNTS
#===================
module:
  hugoVersion:
    extended: true
    min: "0.148.1"

  mounts:
    # CONTENT
    - source: notes
      target: content
    
    - source: main-pages
      target: content

    - source: content
      target: content

    # ASSETS
    - source: node_modules/bootstrap-icons/icons
      target: assets/icons

    - source: assets
      target: assets